In [3]:
import numpy as np

### PRIMER ARRAY

Se crea el "Array"

In [5]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

#### Obtener información sobre el array

In [17]:
x.ndim # Dimensiones del array

1

In [18]:
x.size # Cantidad de elementos en array

5

In [20]:
x.shape # Forma del array

(5,)

In [22]:
x.dtype # Tipo de sus elementos

dtype('int32')

#### Datos heterogéneos

In [24]:
x = np.array([4, 'Einstein', 1e-7])
x

array(['4', 'Einstein', '1e-07'], dtype='<U32')

Aunque, a priori, puede parecer que estamos mezclando tipos enteros, flotantes y cadenas de texto, lo que realmente se produce (de forma implícita) es una coerción 2 de tipos a Unicode:

___

#### Tipos de datos

In [10]:
# Si no se especifica el tipo de dato, por defecto int hace referencia a "int64" y float a "float64"
a = np.array(range(1,6), dtype='int32')
a

array([1, 2, 3, 4, 5])

In [6]:
a.dtype

dtype('int32')

Es posible convertir el tipo de datos que almacena un array

In [9]:
# Para esto usaremos el metodo 'astype'
c = a.astype(float)
c.dtype

dtype('float64')

### MATRICES

#### Creacion De Matrices:

In [13]:
m = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]])
m

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
m.ndim # bidimensional

2

In [100]:
m.size # Cantidad de elementos

NameError: name 'm' is not defined

In [16]:
m.shape # 4 filas, 2 columnas

(4, 3)

In [17]:
m.dtype

dtype('int32')

- EJERCICIO

In [33]:
# Array 1
a = np.array([88,23,39,41])
print(a,'\n')
# Array 2
b = np.array([[76.4,21.7,38.4],[41.2,52.8,68.9]])
print(b,'\n')
# Array 3
c = np.array([[12],[4],[9],[8]])
print(c)

[88 23 39 41] 

[[76.4 21.7 38.4]
 [41.2 52.8 68.9]] 

[[12]
 [ 4]
 [ 9]
 [ 8]]


#### Cambiando La Forma

In [13]:
a = np.array(range(1,13))
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
np.reshape(a, (3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Si solo queremos un numero determinado de filas o columnas, podemos dedjar la otra dimension a -1

In [23]:
np.reshape(a,(6,-1))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

### ALMACENANDO **ARRAYS**

In [28]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Almacenamiento en formato binario propio: Metodo **save()**

In [29]:
np.save('my_matrix', M)

In [31]:
M_reloaded = np.load('my_matrix.npy')
M_reloaded

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Almacenamiento en formato plano: Metodo **savetxt()**

In [32]:
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
np.savetxt('my_matrix.csv', M, fmt='%d')

In [39]:
M_reloaded = np.loadtxt('my_matrix.csv', dtype=int)
M_reloaded

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Desempaquetando valores

In [40]:
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
col1, col2, col3 = np.loadtxt('my_matrix.csv', unpack=True, dtype=int)

In [48]:
col1

array([1, 4, 7])

In [49]:
col2

array([2, 5, 8])

In [50]:
col3

array([3, 6, 9])

### FUNCIONES PARA CREACION DE **ARRAYS**

#### valores fijos:

##### Ceros

In [53]:
np.zeros((3,4), dtype=int)
#Por defecto trabaja con valores "floats"

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

Crear un array **ceros** con las mismas dimensiones que otro array

In [55]:
M = np.array([[1,2,3],[4,5,6]])
M

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
np.zeros_like(M)

array([[0, 0, 0],
       [0, 0, 0]])

In [58]:
np.zeros(M.shape, dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

##### Unos

In [59]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

También existe **np.ones_like()**

##### Mismo Valor

In [60]:
np.full((3,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

También existe **np.full_like()**

##### Matriz Identidad

In [61]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

##### Matriz Diagonal

In [62]:
np.diag([5,4,3,2,1])

array([[5, 0, 0, 0, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 1]])

#### Ejercicio

Cree la siguiente matriz mediante código Python:

Obtenga igualmente las siguientes características de cada uno de ellos: dimensión, tamaño, forma y tipo de sus elementos.

In [64]:
x = np.diag(range(50))
x

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  1,  0, ...,  0,  0,  0],
       [ 0,  0,  2, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 47,  0,  0],
       [ 0,  0,  0, ...,  0, 48,  0],
       [ 0,  0,  0, ...,  0,  0, 49]])

In [76]:
print(f'Las dimensiones son: {x.ndim}')
print(f'El tamaño o cantidad de elementos: {x.size}')
print(f'La figura tiene proporciones de: {x.shape}')
print(f'El tipo de los elementos son: {x.dtype}')

Las dimensiones son: 2
El tamaño o cantidad de elementos: 2500
La figura tiene proporciones de: (50, 50)
El tipo de los elementos son: int32


### VALORES FLOTANTES EQUIESPACIADOS

#### Funcion **arange()**

Funciona exactamente igual que **range()**

In [83]:
a = np.arange(1,13) # Es posible usar flotantes
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### Funcion **linspace()**

Su comportamiento es similar a **arange()**, pero para valores flotantes

##### Especificando limites

In [87]:
# np.linspace(inicio, final, limite superior)
np.linspace(6,60)
# Por defecto "np.linspace()" genera 50 elementos de limite superior

array([ 6.        ,  7.10204082,  8.20408163,  9.30612245, 10.40816327,
       11.51020408, 12.6122449 , 13.71428571, 14.81632653, 15.91836735,
       17.02040816, 18.12244898, 19.2244898 , 20.32653061, 21.42857143,
       22.53061224, 23.63265306, 24.73469388, 25.83673469, 26.93877551,
       28.04081633, 29.14285714, 30.24489796, 31.34693878, 32.44897959,
       33.55102041, 34.65306122, 35.75510204, 36.85714286, 37.95918367,
       39.06122449, 40.16326531, 41.26530612, 42.36734694, 43.46938776,
       44.57142857, 45.67346939, 46.7755102 , 47.87755102, 48.97959184,
       50.08163265, 51.18367347, 52.28571429, 53.3877551 , 54.48979592,
       55.59183673, 56.69387755, 57.79591837, 58.89795918, 60.        ])

In [89]:
np.linspace(6,60,20) # Con 20 valores de limite superior

array([ 6.        ,  8.84210526, 11.68421053, 14.52631579, 17.36842105,
       20.21052632, 23.05263158, 25.89473684, 28.73684211, 31.57894737,
       34.42105263, 37.26315789, 40.10526316, 42.94736842, 45.78947368,
       48.63157895, 51.47368421, 54.31578947, 57.15789474, 60.        ])

In [93]:
# "endpoint" hace que solo tenga 1 decimal
np.linspace(6,60,20, endpoint=False)

array([ 6. ,  8.7, 11.4, 14.1, 16.8, 19.5, 22.2, 24.9, 27.6, 30.3, 33. ,
       35.7, 38.4, 41.1, 43.8, 46.5, 49.2, 51.9, 54.6, 57.3])

### VALORES ALEATORIOS

#### Valores Aleatrorios Enteros

##### Escalar

In [97]:
np.random.randint(3,30)

3

##### Vector

In [98]:
np.random.randint(3,30, size=9)

array([ 9, 13, 25, 29, 11, 12, 17, 19,  8])

##### Matriz

In [99]:
np.random.randint(3,30, size=(3,3))

array([[23, 29, 18],
       [27, 23, 19],
       [26, 25,  6]])

#### Valores Aleatorios Flotantes